### ISSUE TITLE
[FEATURE]: a feature to resize pictures in the wysiwyg mode

### ISSUE THREAD

**Issue by yu2chuan** [drl990114/MarkFlowy#113]
**Is your feature request related to a problem? Please describe.**
resize pictures in the wysiwyg mode

**Describe the solution you'd like**
I expect we can use mouse to resize pictures in the wysiwyg mode

**Describe alternatives you've considered**
right-click the image to input the size such as 1024 x 700.

**Additional context**
None

**Comment by halodong** [comment]
Good idea, we will consider joining in the future, but not in the near future as there are more higher priority tasks to be done.

**Comment by yu2chuan** [comment]
If resize pictures with mouse in the wysiwyg mode can't be done very soon, supporting <img title="" src="https://drive.google.com/uc?id=xxxxxxxxx" alt="" data-align="left" width="200">can be a short-term solution?

**Comment by halodong** [comment]
#114

**Comment by drl990114** [comment]
https://github.com/drl990114/MarkFlowy/releases/tag/v0.7.0
