### ISSUE TITLE
[BUG]: a bug about the connection between two panels in dual mode

### ISSUE THREAD

**Issue by yu2chuan** [drl990114/MarkFlowy#168]
**Describe the bug**
In dual mode, two panels could follow the headline markers \# \## to align the contents. 

**To Reproduce**
1. Open any Markdown file with header markers and long content.
2. Keep scrolling down the page.
3. In the long content, users will encounter difficulty finding the corresponding content in another panel.

**Expected behavior**
Two panels can align the content by headline markers. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win 10
 - Version 0.0.8

**Additional context**
Search feature only work in the Wysiwyg page. That means I can't use search to indirectly find the headline what I want to modified.

**Comment by halodong** [comment]
The current experience here is indeed not good enough. Your suggestion is very good, and we will optimize this.

**Comment by drl990114** [comment]
Currently, dualmoshi has been disabled and will not be supported in the short term. Please close this issue for now.
