### ISSUE TITLE
[FEATURE]: a feature to allow customized theme

### ISSUE THREAD

**Issue by yu2chuan** [drl990114/MarkFlowy#243]
**Is your feature request related to a problem? Please describe.**
Currently, the dark theme and light theme are nice and pretty. I don't expect to add some options in the settings to adjust the style or theme. However, I would like to know where I can get a template to create a theme.css and what the path or folder is for a customized theme.
Frankly, current max-width is too narrow when I use a wide screen.

**Describe the solution you'd like**
I don't expect  a UI to adjust the style. I just need to a css template and where to put this css file.

**Describe alternatives you've considered**
If a customized theme isn't allowed,  please consider to add font family, headline color, max-width options in the settings.

**Additional context**
N/A

**Comment by halodong** [comment]
Thank you for your suggestion and praise！

Currently, custom styles are not supported,, this may not be launched soon until other features are stable and improved.

Regarding the width of the edited content, it may be considered to add settings, and customizing themes also focuses more on providing the ability to customize colors and fonts.

**Comment by drl990114** [comment]
https://github.com/drl990114/MarkFlowy/releases/tag/v0.7.0
