### ISSUE TITLE
[FEATURE]: a feature to "close others"

### ISSUE THREAD

**Issue by yu2chuan** [drl990114/MarkFlowy#274]
**Is your feature request related to a problem? Please describe.**
When you open more and more files, users may need a quick way to close most of them at once.

**Describe the solution you'd like**
right-click mouse on a open file and choose to "close others". Then only keep one and close other opened files at once.

**Describe alternatives you've considered**
You may have the other idea to do the similar thing. Now, I click several files to find somthing due to searching all files in a folder not ready, and then I have to close them one by one. 

**Additional context**

**Comment by halodong** [comment]
I have also thought about this feature, but there are still a lot of higher priority things to do, and I will complete it at a suitable time. thank you for your feedback.
