### ISSUE TITLE
[FEATURE]: a feature to duplicate a md file

### ISSUE THREAD

**Issue by yu2chuan** [drl990114/MarkFlowy#281]
**Is your feature request related to a problem? Please describe.**
Besides add/delete md files, I expect the linebyline can do some simple file management like moving a md file to another folder or duplicating  a md file for revision.

**Describe the solution you'd like**
add "move md file" and "duplicate md file" with add/delete md files

**Describe alternatives you've considered**

**Additional context**

**Comment by halodong** [comment]
Good idea, This will be added to todo list.
