### ISSUE TITLE
[FEATURE]: a feature to select the level of a table of contents

### ISSUE THREAD

**Issue by yu2chuan** [drl990114/MarkFlowy#288]
**Is your feature request related to a problem? Please describe.**

A table of contents is a great feature. It can be better if user can select how many levels they desire to see.

**Describe the solution you'd like**

add a bar or something on the top of a table of contents. Users can use is to choose how many levels they want to see.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by halodong** [comment]
Thank you for your feedback, we will enhance the display effects and functions of this part.
