### ISSUE TITLE
[FEATURE]: a feature to jump to the line where the phrase I'm looking for is

### ISSUE THREAD

**Issue by yu2chuan** [drl990114/MarkFlowy#300]
**Is your feature request related to a problem? Please describe.**

After searching a phrase in the whole folder, users like me will desire to jump to that line in that md file.

**Describe the solution you'd like**

 jump to the line where the phrase I'm looking for is

**Describe alternatives you've considered**

**Additional context**

**Comment by halodong** [comment]
This should be a bug in windowsOS.

**Comment by yu2chuan** [comment]
good. wait for the next release.

**Comment by drl990114** [comment]
There are still some changes that are not yet complete and will be released in about one to two weeks.
