### ISSUE TITLE
[FEATURE]: a feature of parsing <ruby><rt></rt></ruby> while copy from website or paste into MS outlook

### ISSUE THREAD

**Issue by yu2chuan** [drl990114/MarkFlowy#303]
**Is your feature request related to a problem? Please describe.**

When I copy some contents with \<ruby>\<rt>\</rt>\</ruby> from the website and paste into Linebyline, currently Linebyline cannot exactly show the contents with the same way on the Linebyline. However, I know at least "Marktext" can do this.
Whe I copy some contents with \<ruby>\<rt>\</rt>\</ruby> and paste them into MS outlook, currently Linebyline cannot exactly show the contents with the same way on the Linebyline. However, I know at least "Marktext" can do this.

**Describe the solution you'd like**

I expect the linebyline can correctly show \<ruby>\<rt>\</rt>\</ruby> format when they are copied from website or paste into MS outlook.

**Describe alternatives you've considered**

**Additional context**

Website for your test https://trans.hiragana.jp/ruby/https://takoboto.jp/?q=jamashite
md file for your test https://drive.google.com/file/d/18AYJ6jBIqEyG3hyoZEqAtkGXQALqr_bP/view?usp=sharing

**Comment by drl990114** [comment]
Thank you for your feedback. This is indeed a very important feature. The entire feature is already in the development plan. Please wait a moment.
