### ISSUE TITLE
[BUG]: a bug on Ctrl+H

### ISSUE THREAD

**Issue by yu2chuan** [drl990114/MarkFlowy#304]
**Describe the bug**

If I click "Hide" in the menu, I don't know how to wake up the Linebyline again. Ctrl+H seems not to work as a switch between hide and unhide.

**To Reproduce**
1. Go to menu and click Hide
2. Linebyline disappears.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

 - OS: Win 10
 - Version 0.5.2

**Additional context**

**Comment by drl990114** [comment]
It should be a problem with the Windows version. We plan to fix it when the UI is adjusted. The entire menu will be adjusted.

**Comment by drl990114** [comment]
#332
