### ISSUE TITLE
[BUG]: a bug about highlight color <mark> </mark>

### ISSUE THREAD

**Issue by yu2chuan** [drl990114/MarkFlowy#313]
**Describe the bug**

highlight color or \<mark>\</mark> is not obvious in both light/dark theme. May I suggest you use background-color:Coral? Or it can be customized by users in the later version?

**To Reproduce**
1. Open any md file.
2. add \<mark> to highlight some key items
3. switch between light and dark theme.
4. the highlight color can't get the attention.

**Expected behavior**

Suggest orange-like color such as background-color:Coral.

**Screenshots**

**Desktop (please complete the following information):**

 - OS: Win10
 - Version 0.5.3

**Additional context**
Any shortcut or combination key can be used to add <mark></mark> in the content?

**Comment by drl990114** [comment]
Custom themes will be supported in the future.

**Comment by drl990114** [comment]
https://github.com/drl990114/MarkFlowy/releases/tag/v0.7.0
