### ISSUE TITLE
[BUG]: a bug about "File is not exist" in bookmark

### ISSUE THREAD

**Issue by yu2chuan** [drl990114/MarkFlowy#324]
**Describe the bug**
"File is not exist" pops up when the bookmarked md file has moved to another folder.
After removing the file from the bookmark list, "File is not exist" can't be removed until next startup.

**To Reproduce**
1. bookmark one md file.
2. close MarkFlowy and move the bookmarked md file to the other folder.
3. open MarkFlowy and click that md file in the bookmark.
4. "File is not exist" appears.
5.  remove the md file from the bookmark. 
6.  "File is not exist" will not disappear until not startup.

**Expected behavior**
The message should disappear immediately after the md file is removed from the bookmark list.

**Screenshots**

**Desktop (please complete the following information):**

 - OS: Win10
 - Version 0.5.3
 
**Additional context**

"File is not exist" may be revised to "The file does not exist."

**Comment by drl990114** [comment]
Good suggestion, will be added in next version.

**Comment by yu2chuan** [comment]
The newer version could be released this week?

**Comment by drl990114** [comment]
Will be released tonight
