### ISSUE TITLE
[BUG]: a bug abour parsing table markdown

### ISSUE THREAD

**Issue by yu2chuan** [drl990114/MarkFlowy#325]
**Describe the bug**

Copy a Markdown table from the other editor or generated by any Chat AI robot, and paste it into the MarkFlowy editor.
The Markdown table will not be parsed immediately, so users must switch between different modes to show it correctly.

**To Reproduce**
1. Ask any Chat robort to reply answer in a markdown table.
2. Copy the markdown table into MarkFlowy editor.
3. The table will look like source code in the editor.
4. Users must switch between different modes to show it correctly.

**Expected behavior**
copy/paste the markdown table which should be presented immediately and correctly 

**Screenshots**

**Desktop (please complete the following information):**

 - OS: Win10
 - Version 0.5.3

**Additional context**

**Comment by drl990114** [comment]
duplcate #303

**Comment by drl990114** [comment]
Thank you for your feedback. This is indeed a very important feature. The entire feature is already in the development plan. Please wait a moment.

**Comment by yu2chuan** [comment]
version 0.71 and 0.72 have been removed. should I go back to 0.62? Any risk if I continue using 0.71 or 0.72?

**Comment by drl990114** [comment]
0.7.x has a problem that the window size cannot be changed on Windows. It is expected to be fixed after Tauri releases the beta version next week. If this problem has a great impact on you, you can return to 0.6.x. If it is acceptable, you can Wait for the release of the next version.
