### ISSUE TITLE
[BUG]: Some image can not be load in windowsOS

### ISSUE THREAD

**Issue by yu2chuan** [drl990114/MarkFlowy#326]
**Describe the bug**

change the line by "Shift+Enter" and then input  "> ".
The "> " after "Shift+Enter" will not be parsed immediately, so users must switch between different modes to show it correctly.

**To Reproduce**
1. Open any md file and input something.
2. change the line by "Shift+Enter" and then input  "> ".
3. The "> " will not be parsed immediately.
4. users must switch between different modes to show it correctly.

**Expected behavior**
"> " after "Shift+Enter" should be parsed right away and showed correctly.

**Screenshots**

**Desktop (please complete the following information):**

 - OS: Win10
 - Version 0.5.3

**Additional context**

**Comment by drl990114** [comment]
Please try "> " after "Space".

**Comment by yu2chuan** [comment]
I just tried "> " after a space. The result didn't change. 
I still need to switch to anothe mode and come back. Or it will not be parsed.

**Comment by drl990114** [comment]
I tried   "> " after "Space" on windowsos and it is working, Did you enter it in a new paragraph?

**Comment by yu2chuan** [comment]
most files look OK on 0.6.2
could you try to add this photo link in the md. it still can't be displayed correctly.
\!\[](https://i2.kknews.cc/SIG=1of3siu/5qr00060rss39243533.jpg)
![](https://i2.kknews.cc/SIG=1of3siu/5qr00060rss39243533.jpg)

**Comment by drl990114** [comment]
This image format is not taken into account. It is regarded as a local image, so the display will not take effect. Optimize it in the next version.

**Comment by drl990114** [comment]
Currently, only images starting with `http` or `https` will be processed normally.

**Comment by drl990114** [comment]
@yu2chuan I tried this issue again. It seems that the image link has been encrypted. If the original link is copied to the browser, the resulting link is https://i2.kknews.cc/AanuKHnbuZumhJnI6aQELMg8V9t0PHuOlFXErg/0.jpg This can be displayed normally.

**Comment by yu2chuan** [comment]
I don't quite understand what you mean. You mean that \!\[\](https://i2.kknews.cc/SIG=1of3siu/5qr00060rss39243533.jpg) can be correctly displayed on the coming version? Or you mean users have to do some tricks to transfer encrypted hyperlink to  something like https://i2.kknews.cc/AanuKHnbuZumhJnI6aQELMg8V9t0PHuOlFXErg/0.jpg?

**Comment by drl990114** [comment]
[i2.kknews.cc/SIG=1of3siu/5qr00060rss39243533.jpg](https://i2.kknews.cc/SIG=1of3siu/5qr00060rss39243533.jpg) this url is encrypted or rather, it's not a real link, it's redirected to a new connection.  I have tried mainstream editing software but cannot achieve this.

If you copy it to a browser and open it, you will find that the original link has been redirected to [https://i2.kknews.cc/AnanuKHnbuZumhJnI6aQELMg8V9t0PHuOlFXErg/0.jpg](https://i2.kknews.cc/AnanuKHnbuZumhJnI6aQELMg8V9t0PHuOlFXErg/0.jpg)， This can be displayed normally in markflowy 0.6.2,

**Comment by drl990114** [comment]
Directly use the format `i2. kknews. cc/SIG=1of 3siu/5qr00060rss39243533.jpg`, which is not supported in the short term because it does not have a good differentiation from local links. I have not yet come up with a good solution, and I have tried third-party mainstream software, but there is no direct access to this format.

you can try this in markflowy 0.6.2（add `https://` prefix）

```markdown
![Img](https://i2.kknews.cc/SIG=1of3siu/5qr00060rss39243533.jpg)
```

**Comment by yu2chuan** [comment]
I can't follow you well. However, I test the expressions on notepads. (https://github.com/0x7c13/Notepads)

\!\[Img](https://i2.kknews.cc/SIG=1of3siu/5qr00060rss39243533.jpg)

It seems Notpads can correctly display it. I don't know if you can see why Notepads can do this on its site.

**Comment by drl990114** [comment]
<img width="1512" alt="image" src="https://github.com/drl990114/MarkFlowy/assets/48054715/a0506163-ff5c-4f32-a23c-98c19a931fef">



this is also can work in markflowy.
```markdown
![Img](https://i2.kknews.cc/SIG=1of3siu/5qr00060rss39243533.jpg)
```

but this is not work, Notepads won’t work either.

```markdown
![Img](i2.kknews.cc/SIG=1of3siu/5qr00060rss39243533.jpg)
```

What I mean is that you need to make sure that your image link has an `https` or `http` prefix

**Comment by yu2chuan** [comment]
test md file https://drive.google.com/file/d/1Dm-Y3bozrtLSV813cArvi7kpXzuNgg6o/view?usp=sharing
photo evidence  https://drive.google.com/file/d/1Nv5pfY0zucBavMbywcVtiNXOJNmD6xBB/view?usp=sharing
I do have "https", however, it doesn't display photo as you did. Do you know what else I should check?

**Comment by drl990114** [comment]
This should be MarkFlowy in windowsOS bug, macOS is ok.

**Comment by drl990114** [comment]
Try to fix it in the next version.

**Comment by yu2chuan** [comment]
I really expect a version that can fix this problem. Did you find the solution?

**Comment by drl990114** [comment]
It is being investigated and we will try to solve it in the next version.
