### ISSUE TITLE
[BUG]: a bug for ![test]()

### ISSUE THREAD

**Issue by yu2chuan** [drl990114/MarkFlowy#340]
**Describe the bug**
\!\[test]()

**To Reproduce**
1. Open any md file
2. input \!\[test]() in the Wysiwyg mode.
3. switch to source code mode
4. switch back to Wysiwyg mode and the program will hang.

**Expected behavior**

the program should be able to ignore or highlight when it can't successfully render the source code.

**Screenshots**

**Desktop (please complete the following information):**

 - OS: Win10
 - Version 0.6.1

**Additional context**

**Comment by yu2chuan** [comment]
For example: https://drive.google.com/file/d/1CKKSAny7T3ieiS7OZ__jwsiRA1givx8K/view?usp=drive_link
the above md file can be opened by Marktext and linebyline 0.5.2. But 0.61 can't open it and the program will hang or freeze. When the program hangs, I observe there is always a Edge WebView2 there. I never used Microsoft edge but I still updated it to the latest. Obviously, it didn't help the siutation I met on 0.6.1.

**Comment by drl990114** [comment]
I have reproduced the problem. It should be caused by supporting local image preview. I will fix it as soon as possible. Please use 0.5.3 first.

**Comment by drl990114** [comment]
Webview2 is enabled in the background because markflowy uses the `tauri` framework. `Tauri` will use the native webview instead of being built into the software.
