### ISSUE TITLE
[FEATURE]: a feature to zoom in and out with ctrl+mouse wheel

### ISSUE THREAD

**Issue by yu2chuan** [drl990114/MarkFlowy#353]
**Is your feature request related to a problem? Please describe.**

zoom in and zoom out editor area with ctrl+bouse wheel

**Describe the solution you'd like**

Even though users could be able to control the font size in the later version with theme editor, users still sometimes need to zoom in/out the editor area for some reasons.

**Describe alternatives you've considered**

Microsoft Magnifier may be a solution. But, personally, I don't think Magnifier is easy to use.

**Additional context**

**Comment by drl990114** [comment]
Regarding this function, are you mainly concerned about the width of the editor area ,or the font size, or something else?

**Comment by yu2chuan** [comment]
When I am reading Korean or Japanese, I would like the text to appear larger, as those languages are more difficult to read at a smaller size. Conversely, when reading English or European languages, the current size is ideal. If I can change the font size any time, that will be good. especially, I guess I will have Presbyopia very soon.
If the program can handle this feature without a significant decrease in performance, it would be a welcome addition.

**Comment by drl990114** [comment]
ok, the next version will support related settings.
