### ISSUE TITLE
[BUG]: "request error, please check your ApiKey is it right or not setting"

### ISSUE THREAD

**Issue by yu2chuan** [drl990114/MarkFlowy#362]
**Describe the bug**
Recently, I can't use chat. "request error, please check your ApiKey is it right or not setting" pops up.
Then I applied a new API key. The same message still pops up.

**To Reproduce**
1. Go to Chat
2. Input anythng such as Hello.
3. "request error, please check your ApiKey is it right or not setting" pops up.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

 - OS: Win10
 - Version 0.6.2

**Additional context**

**Comment by drl990114** [comment]
I haven't reproduced it yet. Currently, my own way of obtaining apiKey is blocked, and there is no good way to test it. I will consider how to adjust it in the future
