### ISSUE TITLE
[FEATURE]: a shotcut to add tables

### ISSUE THREAD

**Issue by yu2chuan** [drl990114/MarkFlowy#379]
**Is your feature request related to a problem? Please describe.**
creating a table appears it has been remove from the menu in the new UI. is it possible to add a shortcut to create a table?

**Describe the solution you'd like**
any ways to quickly add a table by either a shortcut or right-click mouse

**Describe alternatives you've considered**

**Additional context**

**Comment by drl990114** [comment]
Good suggestion, I will add it to my recent development plans
