### ISSUE TITLE
File explorer bug

### ISSUE THREAD

**Issue by aunjaffery** [drl990114/MarkFlowy#400]
I opened the folder from bottom left option "open folder"
there is no option to create new file. unless a folder already have sub folder inside. i can right click sub folder to create new file. but There is no option to create file in root folder which i opened.
Also there should be a warning before deleting file and folder. I accidentally deleted my whole folder :(

**Comment by drl990114** [comment]
Thank you for your feedback, it has been included in the recent development plan.
