### ISSUE TITLE
[FEATURE]: either report an issue or switch to source code mode

### ISSUE THREAD

**Issue by yu2chuan** [drl990114/MarkFlowy#442]
**Is your feature request related to a problem? Please describe.**
When md file includes an not parsing code, the markflowy can provide another choice is to switch to source code mode.

Example:
One of my md files includes a statement as below. the markflowy can't accept this and show a "Something went wrong."

<iframe id="google_ads_iframe_/21787810958,110393698/DE_commonhealth.com_ros_kb_content03a_0" name="google_ads_iframe_/21787810958,110393698/DE_commonhealth.com_ros_kb_content03a_0" title="3rd party ad content" width="300" height="250" scrolling="no" marginwidth="0" marginheight="0" frameborder="0" role="region" aria-label="Advertisement" tabindex="0" sandbox="allow-forms allow-popups allow-popups-to-escape-sandbox allow-same-origin allow-scripts allow-top-navigation-by-user-activation" style="border: 0px; vertical-align: bottom;" data-load-complete="true" data-google-container-id="5"></iframe>

**Describe the solution you'd like**
1. showing something in the editor to let users know some statements can't be recoginized.
2. besides "something went wrong", the software may provide an option to switch editor to the source code mode.

**Describe alternatives you've considered**

**Additional context**

**Comment by drl990114** [comment]
Theoretically, this will be solved in 0.7.0, but the Windows version currently needs to wait for Tauri's bug to be resolved before it can be released.

**Comment by yu2chuan** [comment]
I am not sure if this related to Tauri's bug or not. In the light theme, the unselect checkbox looks like a solid black box. Hope the Taur can release the new version soon.

**Comment by drl990114** [comment]
This should be a platform compatibility issue, I will fix it in the next version

**Comment by drl990114** [comment]
This issue in v0.7.2 should be fixed.
