### ISSUE TITLE
Silent crash on Windows 7

### ISSUE THREAD

**Issue by sergeevabc** [drl990114/MarkFlowy#478]
Windows 7 x64, MarkFlowy 0.7.2.0

Launch and see that nothing happens, there isn't even an error message.

**Comment by drl990114** [comment]
Please download a version 0.6.2 and see if it works. Currently, 0.7.2 and 0.7.1 need to wait for Tauri's bug [https://github.com/tauri-apps/tauri/issues/8645] fix and published.

**Comment by sergeevabc** [comment]
MarkFlowy 0.6.2 does not work either, alas.

**Comment by drl990114** [comment]
Sorry, I currently don’t have a Windows 7 device, so it’s not easy to troubleshoot. It will take some time to fix it. I will let you know when the fix is confirmed.

**Comment by drl990114** [comment]
v10.0.2 fixed the unresponsive issue on Win7, but I don't have any testing equipment around me to ensure that this issue has been fixed. Thank you very much if you could help me take a look.

**Comment by drl990114** [comment]
There is no relevant feedback recently, so this issue is temporarily closed.
