### ISSUE TITLE
when the md file is a little bigger, the input response is obviously slower and delayed in the editor.

### ISSUE THREAD

**Issue by yu2chuan** [drl990114/MarkFlowy#519]
**Describe the bug**
when the md file is a little bigger, the input response is obviously slower and delayed in the editor.

**To Reproduce**
1. create a md file.
2. add 1000 words into the contents
3. so far, the input response looks ok.
4. add more words to make the contents up to 5000 words.
5. input "..."; then "..." will take about 0.5~1sec to show on the editor.
6. while giving more and more words up to 20000 words, the input response will delay about 3 sec. I only input "..." (3 periods) as a simple test.

**Expected behavior**
the md file isn't really huge. users should see what they input in real time.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win10
 - Version 0.7.6

**Additional context**
a file for your test(https://drive.google.com/file/d/15mt2YeID0OUX8X1th6IopK_hUBQpb6rz/view?usp=sharing)

**Comment by drl990114** [comment]
Performance is an issue worthy of attention, I will pay attention to and optimize this issue.

**Comment by yu2chuan** [comment]
Can you reproduct what I said? I do expect this can be improved soon. I always have to wait for a while after typing something to confirm the contents.

**Comment by drl990114** [comment]
I have other things going on this month and there is no way to fix this problem anytime soon.

How many tabs do you have open? It would be better to reduce the number of tabs.

**Comment by yu2chuan** [comment]
Understood.  I like the markflowy than the others. I can wait. Basically,

**Comment by drl990114** [comment]
Thank you for your recognition, I will try my best to make it better
