### ISSUE TITLE
[FEATURE]: show sidebar tab labels/clarifications on hover

### ISSUE THREAD

**Issue by keunes** [drl990114/MarkFlowy#613]
**Is your feature request related to a problem? Please describe.**

I've just installed the app and don't know what the different tabs are/do.

**Describe the solution you'd like**

Help me explore & understand the AI by displaying tab labels on hover (with a slight delay, of course, so that it's not bothering in daily use).

**Describe alternatives you've considered**

Replacing the icons with text-based tabs - that would be too long.

**Additional context**

![image](https://github.com/drl990114/MarkFlowy/assets/11229646/62a5aecd-2fdb-4564-9988-2eceeacd31df)
The pointer is not shown in the screenshot, but I'm hovering the most-right icon here.

**Comment by drl990114** [comment]
Thank you, this is a very good suggestion
