### ISSUE TITLE
[BUG]: Button to make full window actually makes fully full-screen

### ISSUE THREAD

**Issue by keunes** [drl990114/MarkFlowy#614]
**Describe the bug**

When cycling through the window size options, there is no way to have the application open in normal full window (where you still see the bar).

**To Reproduce**

MarkFlowy opens full-screen, but even blocks the windows bar.

**Expected behavior**

MarkFlowy opens full-screen, but still showing the windows bar.

**Screenshots**

![3SdJQUKSVP](https://github.com/drl990114/MarkFlowy/assets/11229646/f00e12ac-6855-4447-96fd-773254d297cf)

**Desktop (please complete the following information):**

 - OS: Windows 11
 - Version: 0.8.0
TauriVersion: 2.0.0-beta.7

**Additional context**

**Comment by drl990114** [comment]
Tauri's problem, but it can't be upgraded yet because there are other problems that need to be solved later.
