### ISSUE TITLE
The table of contents doesn't refresh while switching different md files

### ISSUE THREAD

**Issue by yu2chuan** [drl990114/MarkFlowy#615]
**Describe the bug**
The table of contents doesn't refresh while switching different md files

**To Reproduce**
1. open at least two md files which include headlines
2. click the table of contents in the left panel.
3. switch between the opened md files
4. the table of contents didn't change contents accordingly.

**Expected behavior**
The table of contents should refresh the contents while switching different md files

**Screenshots**

**Desktop (please complete the following information):**

 - OS: Win10
 - Version:0.8

**Additional context**

**Comment by drl990114** [comment]
This bug has been fixed and will be released in the next version.
