### ISSUE TITLE
[BUG]: cmd + A don't work properly on macOS arm64

### ISSUE THREAD

**Issue by jiengup** [drl990114/MarkFlowy#617]
**Describe the bug**

cmd + A don't work properly on macOS arm64

**To Reproduce**

1. create a code block using ` ``` `
2. switch syntax to c++
3. press cmd + A
4. it selects everything and press delete don't work

**Expected behavior**

it supposes to only select the text in the code block.

**Desktop (please complete the following information):**

 - OS: MacOS arm64
- AppName: MarkFlowy
- Version: 0.9.0
- TauriVersion: 2.0.0-beta.7

**Comment by drl990114** [comment]
It was fixed in v0.9.1.
