### ISSUE TITLE
a feature about file name

### ISSUE THREAD

**Issue by yu2chuan** [drl990114/MarkFlowy#628]
**Is your feature request related to a problem? Please describe.**
when a new file name is created with special characters like \: or \?, the file name will be invalid and wait for correction.
On Windows, when a new file name is created with special characters like \: or \?, those special characters will be removed directly from file name after popping a message "a file name can't contain any of the following ...."
If possible, I prefer you follow Windows' way to handle this situation.
Besides adding a new file or deleting a file, can we have rename files and move file to the other folders?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by yu2chuan** [comment]
More about this feature
In the explorer panel, folders/files can be bookmarked, moved, created, or deleted. They will be good for users.

**Comment by drl990114** [comment]
> More about this feature In the explorer panel, folders/files can be bookmarked, moved, created, or deleted. They will be good for users.

This is already under development and should be completed in the next version.

Regarding file names containing special symbols, directly removing them when creating a new file may cause confusion for some users who do not understand the rules.

**Comment by yu2chuan** [comment]
Frankly, regarding file names containing special symbols, I will respect your decision. Basically, Microsoft does this. I believe it's quite safe if Markflowy just follows this software behavior.

**Comment by yu2chuan** [comment]
Thanks for the effort, I saw the rename and new folder in  version 0.10.2. However, I found two small bugs.
1. when users new a file or new a folder, all opened files will be forced to close.
2. when users rename a file, they have to use the keyboard to move the cursor instead of the mouse. If they use the mouse to move the cursor, the rename will disappear or be canceled.

**Comment by drl990114** [comment]
Thank you. It will be released together with the next version later
