### ISSUE TITLE
Opening a folder does not work (Debian)

### ISSUE THREAD

**Issue by Torsten-K** [drl990114/MarkFlowy#639]
**Describe the bug**
Opening a folder after program start does not work, the program freezes. I can only be closed via Task Manager or Terminal.

**To Reproduce**
Start the program under Debian, click on the blue line _Open Folder_.

**Expected behavior**
A file explorer should be opened. This works under Windows, but not Debian.

**Desktop (please complete the following information):**
 - OS: GNU/Linux (Debian 12 Bookworm)
 - Version 0.9.2

**Comment by drl990114** [comment]
This may be related to tauri, we need to wait for tauri2 to stabilize before taking a look. At present, I do not have suitable equipment for debugging, which may take some time to troubleshoot.

**Comment by drl990114** [comment]
According to feedback, the issue has been fixed on 0.11.3.

**Comment by Torsten-K** [comment]
I can confirm that this issue does no longer occurs in 0.11.3 and 0.12.0. Thank you for fixing!
