### ISSUE TITLE
a bug when a table includes merged rows or columns.

### ISSUE THREAD

**Issue by yu2chuan** [drl990114/MarkFlowy#652]
**Describe the bug**
A table includes merged rows or columns in Wysiwyg mode. After switching to source code mode, the merged parts cannot be kept.

**To Reproduce**
1. In Excel, create a table including merged columns.
2. Copy the table from Excel and paste it into md file.
3. Now, the table still looks perfect as it was in Excel.
4. Switch to source code mode
5. move back to Wysiwyg mode, the merged columns have disappeared.

**Expected behavior**
keep what it originally was from Excel.

**Screenshots**

**Desktop (please complete the following information):**

 - OS: Win10
 - Version 0.9.2

**Additional context**

**Comment by drl990114** [comment]
The syntax of markdown should not support merged table cell elements.

**Comment by yu2chuan** [comment]
understood and acceptable.

**Comment by drl990114** [comment]
Thank you for your understanding. Currently, MarkFlowy's goal is to create a good Markdown editor. Temporarily close this issue. It may be reopened at a suitable time in the future.
