### ISSUE TITLE
make the long file name short in the file tab

### ISSUE THREAD

**Issue by yu2chuan** [drl990114/MarkFlowy#653]
**Is your feature request related to a problem? Please describe.**
It's good to open multiple md files. However, it's hard to transition to the other file if one of them has a very long file name.

**Describe the solution you'd like**
When the md file name is longer than a certain number of characters, the markflow only shows one-third of the file name in the file tab. 
You may have the other better idea.

**Describe alternatives you've considered**

**Additional context**

**Comment by drl990114** [comment]
Good suggestion, I think your suggestion is good
