### ISSUE TITLE
a bug about photo link

### ISSUE THREAD

**Issue by yu2chuan** [drl990114/MarkFlowy#678]
**Describe the bug**
some photos can't be displayed again.
https://i2.kknews.cc/SIG=1of3siu/5qr00060rss39243533.jpg
https://drive.google.com/uc?id=1EkjoGd7aVz-ktkMSmql_ZDtUGJszu6f2

**To Reproduce**
1. create a md file
2. use the following link to add markdown photo.
https://i2.kknews.cc/SIG=1of3siu/5qr00060rss39243533.jpg
https://drive.google.com/uc?id=1EkjoGd7aVz-ktkMSmql_ZDtUGJszu6f2
3. they can be displayed in a certain version. but they cannot show correctly on 0.10.2

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win10
 - Version 0.10.2

**Additional context**
![](https://i2.kknews.cc/SIG=1of3siu/5qr00060rss39243533.jpg)
![](https://drive.google.com/uc?id=1EkjoGd7aVz-ktkMSmql_ZDtUGJszu6f2)

**Comment by drl990114** [comment]
<img width="1034" alt="image" src="https://github.com/drl990114/MarkFlowy/assets/48054715/4836c707-a77b-48f7-8a2d-661ca34e2afd">

I tried the previous version but couldn't access it, and I couldn't open this picture in my browser. I also tried other editors but they couldn't load properly.

Have you set access permissions for images and tried to open them in a browser without user information to see if they can be loaded properly?

**Comment by yu2chuan** [comment]
Yes, I think this one, https://i2.kknews.cc/SIG=1of3siu/5qr00060rss39243533.jpg, has changed not to be accessed in these two days. But how about another one? a photo shared on Google drive, https://drive.google.com/uc?id=1EkjoGd7aVz-ktkMSmql_ZDtUGJszu6f2.

**Comment by drl990114** [comment]
These two are the same issue, unable to obtain permissions. Although the link to Google Drive can be opened from the browser, the HTTP request was indeed rejected, with HTTP code 403.

**Comment by yu2chuan** [comment]
I just test 2 links. They are OK to show the photos on 0.9.2 even I didn't login any Google accounts. Then, I tried to open the same file with version 0.10.2. The photos still can't be displayed in the editor. There must be something different between 0.9.2 and 0.10.2. I really count on you knowing what it could be. Or I may need to stay at 0.9.2 forever.

**Comment by yu2chuan** [comment]
One more thing is this link , https://i2.kknews.cc/SIG=1of3siu/5qr00060rss39243533.jpg, can be accessed again. I think the previous restriction was temporary for maintenance or something.

**Comment by drl990114** [comment]
About google drive image can't load, you can look this link https://stackoverflow.com/questions/70798664/google-drive-image-gives-403-forbidden-error



The main reason is that Google has certain restrictions on access permissions, and there are several possible solutions:
1. Set the scope of image sharing to everyone
2. Change the image link to  `https://lh3.googleusercontent.com/d/{ID_OF_THE_FILE}`. I have tried this method and it is indeed possible. Of course, there are also some other links that may require a folder, etc
3. There are also some other solutions in the link that you can try again

**Comment by drl990114** [comment]
> One more thing is this link , [i2.kknews.cc/SIG=1of3siu/5qr00060rss39243533.jpg](https://i2.kknews.cc/SIG=1of3siu/5qr00060rss39243533.jpg), can be accessed again. I think the previous restriction was temporary for maintenance or something.

0.9.2 can only be opened due to caching, as I am currently unable to load these two images on any software or MarkFlowy0.9.2

**Comment by yu2chuan** [comment]
I cleaned all  cookies and cache. Then I tried the following 3 links in 4 softwares.
\!\[](https://drive.google.com/uc?id=1EkjoGd7aVz-ktkMSmql_ZDtUGJszu6f2) ; let me call this link1
\!\[](https://lh3.googleusercontent.com/d/1EkjoGd7aVz-ktkMSmql_ZDtUGJszu6f2) ; let me call this link2
\!\[](https://i2.kknews.cc/SIG=1of3siu/5qr00060rss39243533.jpg) ; let me call this link3

on 0.9.2, it took a second to load images. Link1, 2, 3 can show photos in the markflowy.
on 0.10.2, Link2 can show the photo in the markflowy.
on AnyType, Link1, 2, 3 can show photos correctly.
on Inkdown, Link 2, 3 can show photos correctly.

I still believe there should be something different on 0.9.2.

**Comment by drl990114** [comment]
Can't Link3 load normally at present, in v0.10.2 MarkFlowy.

**Comment by drl990114** [comment]
Link2 and Link3 are currently able to load normally on my device. Regarding Link1, I will further study the solution.

**Comment by yu2chuan** [comment]
I don't know if this will impact the program's performance. If the program sees "https://drive.google.com/uc?id=" as "https://lh3.googleusercontent.com/d/", can it be a short term solution?

**Comment by drl990114** [comment]
I have roughly found the reason, which may be due to upgrading the tauri. If there is no solution in the short term, I will first revert back to the tauri version that is consistent with 0.9.2.

**Comment by drl990114** [comment]
Thank you for providing a lot of information. I fixed this issue on v0.11.2.
