### ISSUE TITLE
a bug of find/replace feature

### ISSUE THREAD

**Issue by yu2chuan** [drl990114/MarkFlowy#680]
**Describe the bug**
highlight the wrong term in the find/replace feature

**To Reproduce**
1. Go to any md file in English
2. Ctrl+F to trigger the find/replace feature
3. input something to find and perform replace
4. this feature will highlight the wrong term and replace what it was wrongly highlighted.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

 - OS: Win 10
 - Version 0.11.3

**Additional context**
replacing the wrongly highlighted term will be a little bit critical.

**Comment by drl990114** [comment]
I suspect it was caused by the combination of global search and single file search. If global search is not turned on and only single file search is used, is the result correct?

**Comment by yu2chuan** [comment]
https://drive.google.com/file/d/19w-mqipwMuH4FxBKt68uJ_KAfBF4E6T1/view?usp=drive_link
I don't know when it could go wrong. Please check my test file in the link.
