### ISSUE TITLE
shared photo links from google was changed to <iframe src=....."/>

### ISSUE THREAD

**Issue by yu2chuan** [drl990114/MarkFlowy#703]
**Describe the bug**
I understand some shared photo link should be changed to <iframe scr=..> format, and then it can be shown.
But it accidently changed the shared photo on the google. I think I will spend time to change them back to \!\[]()

For example, 
\!\[](https://drive.google.com/uc?id=1EkjoGd7aVz-ktkMSmql_ZDtUGJszu6f2)
changed to
<iframe src="https://drive.google.com/uc?id=1EkjoGd7aVz-ktkMSmql_ZDtUGJszu6f2"/>

Then, the photo can't be shown in the markflowy.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

 - OS: Win 10
 - Version 0.13.1

**Additional context**

**Comment by drl990114** [comment]
I didn't understand what you said. 

Are you saying that the image links shared by Google now are `iframe`? or are MarkFlowy parsing incorrect?

**Comment by yu2chuan** [comment]
Originally, it should be like this.
\!\[](https://drive.google.com/uc?id=1EkjoGd7aVz-ktkMSmql_ZDtUGJszu6f2)
but one of the markfloy version released recently somehow parsed it to 
<iframe src="https://drive.google.com/uc?id=1EkjoGd7aVz-ktkMSmql_ZDtUGJszu6f2"/>
then it becomes invisible. 
I don't know how it occured, but now I have to manually change them back to the original format ![](google hyperlinks) .
So far, everything looks fine.

**Comment by drl990114** [comment]
This situation has not been reproduced, only copying \!\[](https://drive.google.com/uc?id=1EkjoGd7aVz-ktkMSmql_ZDtUGJszu6f2) will turn it into `<img...>`, There has been no occurrence of`<iframe>`.

This area is currently undergoing refactoring, which may improve the situation you mentioned. However,<iframe>'s support for loading such images may not be easy to achieve.

**Comment by yu2chuan** [comment]
I didn't notice when it started again. 
The photo shared to everyone on the google drive can't be read/seen again regardless of 0.16 or 0.17. I didn't try to install each installation file to test this.
[test.md](https://github.com/user-attachments/files/17891351/test.md)

**Comment by drl990114** [comment]
Is it because the first two iframes cannot be viewed? I can see the pictures behind here

**Comment by yu2chuan** [comment]
When I removed the iframe and changed it to
\!\[](https://drive.google.com/uc?id=1EkjoGd7aVz-ktkMSmql_ZDtUGJszu6f2), I still cannot view the photo on markflowy.
However, I can see this picture in the editor which I'm currently using to input this message on Github.

**Comment by yu2chuan** [comment]
share a good news with you.
When I change the format to \[](https://drive.usercontent.google.com/download?id=1EkjoGd7aVz-ktkMSmql_ZDtUGJszu6f2),
then I can see the photo shared on Google drive.
