### ISSUE TITLE
Unable to modify language settings

### ISSUE THREAD

**Issue by Raven-1027** [drl990114/MarkFlowy#732]
**Describe the bug**
Can Change the language setting in setting page

**To Reproduce**

1. Click on setting icon
2. Choose 'setting'
3. Focus on Miscellaneous > Language
4. Focus on text input field, try to type some text

**Expected behavior**

Refer to field `type` value `select` in `settingSchema.json`. It should be a combo box. However, nothing happened when you focus on this box.

I don't know if this is a intentional design, and just don't work in my environment. I put the screenshots before and after this change.

**This may fix**

Refer to the [example](https://mui.com/material-ui/react-autocomplete/#combo-box) given in material-ui web site, it may caused by the wrong value in [Select.tsx](https://raw.githubusercontent.com/drl990114/MarkFlowy/refs/heads/main/apps/desktop/src/router/Setting/component/SettingItems/Select.tsx) line 35, the value of `renderInput`

```tsx
const SelectSettingItem: React.FC<SettingItemProps<Setting.SelectSettingItem>> = (props) => {
// ...
        renderInput={({ inputProps }) => {
          const { ref, ...rest } = inputProps
          return <div>
          <Input type='text' {...rest} inputRef={ref}/>
        </div>
        }}
// ...
}
```
possible correct may be as following,
```tsx
const SelectSettingItem: React.FC<SettingItemProps<Setting.SelectSettingItem>> = (props) => {
// ...
        renderInput={(params)=><TextField {...params}/>}
// ...
}
```
This change will allow user change the field of language, and such change can be performed after rebooting MarkFlowy

**Screenshots**

0.14.0 looks like:
![Screenshot from 2024-10-04 17-09-06](https://github.com/user-attachments/assets/165bc446-8c14-482e-994c-9ad5fddb9c09)

after such fix:
![Screenshot from 2024-10-04 17-16-44](https://github.com/user-attachments/assets/311d6388-4bbb-460e-a69e-6b0ac83084e5)

**Desktop (please complete the following information):**

- OS: Manjaro Linux
- Winsows Mannager: niri

**Comment by drl990114** [comment]
There is indeed a problem, thank you for the feedback
